all:
    project_dir: "/scr1/users/leej39/Redding"
    fastq_dir: "/scr1/users/leej39/Redding/Redding_Cleaned_Data/concatenated_fastq"
    sample_id: "SampleIDs.txt"
    admin_email: "junglee0713@gmail.com"
    fastq_dir: "Redding_Cleaned_Data/concatenated_fastq"

assembly:
    suffix: "assembly"
    min_length: 300
    threads: 4        
